import Head from "next/head";
import { TextProvider } from "@/components/providers/textProvider";
import { GetWeather } from "@/components/uiGroup/getWeather";

export default function Home() {
  return (
    <TextProvider>
      <Head>
        <title>天気情報確認サービス</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/太陽アイコン.svg" />
      </Head>
      <GetWeather />
    </TextProvider>
  );
}
